stages:
  - security

variables:
  IMAGE_NAME: "financial-api"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  DOCKER_TLS_CERTDIR: ""

security_scan:

  stage: security

  image: docker:24

  services:
    - docker:24-dind

  before_script:
    - apk add --no-cache curl

  script:

    - docker build -t $IMAGE_NAME:$IMAGE_TAG app/

    - docker run --rm aquasec/trivy:latest image $IMAGE_NAME:$IMAGE_TAG
