stages:
  - build

variables:
  AWS_REGION: "eu-west-2"
  IMAGE_NAME: "financial-api"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build

  image: docker:24

  services:
    - docker:24-dind

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG app/
